[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kvcli"
path = "kvcli/main.rs"

[dependencies]
log = "*"
env_logger = "*"
tokio = { version = "1", features = ["full"] }
windows-core.workspace = true
windows.workspace = true
mssf-core.workspace = true
mssf-com.workspace = true
async-trait = "*" # needed by tonic
tonic = "*"
prost = "*"
clap = { version = "4.5.7", features = ["derive"] }

[dependencies.sfrc-core]
path = "../../libs/core"


[dependencies.sfrc-c]
path = "../../libs/c"

[build-dependencies]
tonic-build = "*"
prost-build = "*"

[package.metadata.rust-analyzer]
cargo.loadOutDirsFromCheck = true
