[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "*"
tokio = { version = "1", features = ["full"] }
windows-core = "0.51"
async-trait = "0.1"

[dependencies.windows]
version = "0.51"
features = [
    "implement"
]

[dependencies.fabric_base]
git = "https://github.com/youyuanwu/service-fabric-rs.git"
rev = "3f2bef6eaa5cbbb1b97ee27fb87205ecc9c5ebdb"
features = [
    "implement",
    "ServiceFabric_FabricCommon",
    "ServiceFabric_FabricCommon_FabricRuntime",
    "Win32_Foundation"
]

[dependencies.fabric_rs]
git = "https://github.com/youyuanwu/service-fabric-rs.git"
rev = "3f2bef6eaa5cbbb1b97ee27fb87205ecc9c5ebdb"

[dependencies.reliable_collection]
path = "../../fabric/reliable_collection"


[dependencies.fabric_c]
path = "../../fabric/c"
features = ["implement"]