[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
env_logger = "*"
tokio = { version = "1", features = ["full"] }
windows-core = "0.54"
async-trait = "*" # needed by tonic
tonic = "*"
prost = "*"

[dependencies.windows]
version = "0.54"
features = [
    "implement"
]

[dependencies.mssf-com]
version = "0.0.3"
features = [
    "implement",
    "ServiceFabric_FabricCommon",
    "ServiceFabric_FabricCommon_FabricRuntime",
    "Win32_Foundation"
]

[dependencies.mssf-core]
version = "0.0.3"

[dependencies.sfrc-core]
path = "../../libs/core"


[dependencies.sfrc-c]
path = "../../libs/c"
features = ["implement"]

[build-dependencies]
tonic-build = "*"
prost-build = "*"

[package.metadata.rust-analyzer]
cargo.loadOutDirsFromCheck = true