[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
env_logger = "*"
tokio = { version = "1", features = ["full"] }
windows-core = "0.51"
async-trait = "*" # needed by tonic
tonic = "*"
prost = "*"

[dependencies.windows]
version = "0.51"
features = [
    "implement"
]

[dependencies.fabric_base]
git = "https://github.com/youyuanwu/service-fabric-rs.git"
rev = "e2a2cd4a4019317061d1fdb043c322719f21399e"
features = [
    "implement",
    "ServiceFabric_FabricCommon",
    "ServiceFabric_FabricCommon_FabricRuntime",
    "Win32_Foundation"
]

[dependencies.fabric_rs]
git = "https://github.com/youyuanwu/service-fabric-rs.git"
rev = "e2a2cd4a4019317061d1fdb043c322719f21399e"

[dependencies.reliable_collection]
path = "../../fabric/reliable_collection"


[dependencies.fabric_c]
path = "../../fabric/c"
features = ["implement"]

[build-dependencies]
tonic-build = "*"
prost-build = "*"

[package.metadata.rust-analyzer]
cargo.loadOutDirsFromCheck = true